--表白墙

CREATE TABLE lovewall(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
uid INT UNSIGNED NOT NULL,
title VARCHAR(30) NOT NULL,
content text NOT NULL,
time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
PRIMARY KEY(id),
FOREIGN KEY(UID) REFERENCES person(id)
)DEFAULT CHARSET = utf8mb4;

--表白墙的评论

CREATE TABLE comments(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
uid INT UNSIGNED NOT NULL,
qid INT UNSIGNED NOT NULL,
content text NOT NULL,
time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(id),
FOREIGN KEY(UID) REFERENCES person(id),
FOREIGN KEY(QID) REFERENCES lovewall(id)
)DEFAULT CHARSET = utf8mb4;