
--存储用户的表
CREATE TABLE person(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
username VARCHAR(16) UNIQUE NOT NULL,
password VARCHAR(16) NOT NULL,
sex INT NOT NULL DEFAULT 1,
avatar TEXT DEFAULT NULL,
token VARCHAR(64) DEFAULT NULL,
PRIMARY KEY(id)
)DEFAULT CHARSET = utf8mb4;

--存储快递的表
CREATE TABLE express(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
uid INT UNSIGNED NOT NULL,
deliverstatus INT NOT NULL DEFAULT 0,
repay VARCHAR(20) NOT NULL,
phonenumber VARCHAR(13) NOT NULL,
delivertype VARCHAR(16) NOT NULL,
receivetime VARCHAR(20) NOT NULL,
sendlocation VARCHAR(20) NOT NULL,
note TEXT DEFAULT NULL,
PRIMARY KEY(id),
FOREIGN KEY(UID) REFERENCES person(id)
)DEFAULT CHARSET = utf8mb4;

--存储二手商品的表

CREATE TABLE secondhand(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
uid INT UNSIGNED NOT NULL,
title VARCHAR(50) NOT NULL,
image TEXT DEFAULT NULL,
price VARCHAR(10) NOT NULL,
publishid INT NOT NULL DEFAULT 1,
page INT NOT NULL DEFAULT 200,
phonenumber VARCHAR(13) NOT NULL,
words VARCHAR(16) NOT NULL DEFAULT "10000字",
paper VARCHAR(16) NOT NULL DEFAULT "胶版纸",
format INT NOT NULL DEFAULT 1,
printtime VARCHAR(20) NOT NULL DEFAULT "2018年5月1日",
package VARCHAR(10) NOT NULL DEFAULT "平装",
isbn VARCHAR(16) NOT NULL,
recommended TEXT DEFAULT NULL,
PRIMARY KEY(id),
FOREIGN KEY(UID) REFERENCES person(id)
)DEFAULT CHARSET = utf8mb4;













